<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>coug_rqt</name>
  <version>0.0.0</version>
  <description>RQt dashboards and UI monitoring tools.</description>
  <maintainer email="snelsond@byu.edu">snelsondurrant</maintainer>
  <license>Apache-2.0</license>
  <url type="repository">https://github.com/cougars-auv/coug_rqt</url>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>coug_interfaces</exec_depend>
  <exec_depend>diagnostic_aggregator</exec_depend>
  <exec_depend>dvl_msgs</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>python_qt_binding</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rqt_console</exec_depend>
  <exec_depend>rqt_gui</exec_depend>
  <exec_depend>rqt_gui_py</exec_depend>
  <exec_depend>rqt_robot_monitor</exec_depend>
  <exec_depend>rqt_runtime_monitor</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>

  <test_depend>python3-pytest</test_depend>
  <test_depend>python3-pytest-cov</test_depend>

  <export>
    <build_type>ament_python</build_type>
    <rqt_gui plugin="${prefix}/plugin.xml" />
  </export>
</package>
